# Generated by Django 5.1.1 on 2024-09-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("horse_power", models.IntegerField()),
                ("creation_date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
    ]
