# Generated by Django 5.1.1 on 2024-09-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="creation_date",
            field=models.DateField(null=True),
        ),
    ]
