# Generated by Django 5.1.1 on 2024-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_alter_car_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(max_length=255),
        ),
    ]
