# Generated by Django 5.1.1 on 2024-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0005_alter_car_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="engine_type",
            field=models.CharField(
                choices=[
                    ("ICE", "internal combustion engine"),
                    ("HYBRID", "hybrid engine"),
                    ("ELECTRICAL", "electric engine"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
