# Generated by Django 5.1.1 on 2024-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0006_car_engine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
