# Generated by Django 5.1.1 on 2024-09-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0007_car_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
